name: Docker构建与部署

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 登录DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 构建Docker镜像
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/back-service:${{ github.sha }}

    - name: 推送Docker镜像
      run: docker push ${{ secrets.DOCKER_USER }}/back-service:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: 通过SSH连接并执行远程命令
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          sed -i "s|image:.*back-service.*|image: ${{ secrets.DOCKER_USER }}/back-service:${{ github.sha }}|" docker-compose.yml
          docker-compose pull back-service
          docker-compose up -d --build
